name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]   
    types: [completed]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-apply
  cancel-in-progress: false

jobs:
  apply:
    
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'deployment') }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform

    env:
      TFVARS_B64: ${{ secrets.TFVARS_B64 }}

    steps:
      - name: Checkout (same commit that Plan ran on)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Restore terraform.tfvars from secret
        run: |
          if [ -z "$TFVARS_B64" ]; then
            echo "Missing secret TFVARS_B64"
            exit 1
          fi
          echo "$TFVARS_B64" | base64 -d > terraform.tfvars
          sed -i 's/\r$//' terraform.tfvars
          test -f terraform.tfvars && echo "tfvars restored âœ…"

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan (for apply)
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve tfplan
